# Generated by Django 3.1.7 on 2021-04-07 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('AMS', 'Ams'), ('BMI', 'Bmi'), ('CSE', 'Cse'), ('ECE', 'Ece'), ('N/A', 'None')], default='N/A', max_length=3)),
                ('number', models.IntegerField(default=100)),
                ('lower_credit_limit', models.IntegerField(default=3)),
                ('upper_credit_limit', models.IntegerField(default=3)),
                ('description', models.TextField(default='No class description.', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
                ('days', models.CharField(max_length=10, null=True)),
                ('section', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.course')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrerequisiteSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_required', models.IntegerField(default=1)),
                ('parent_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mast.course')),
                ('parent_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mast.courseprerequisiteset')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('AMS', 'Ams'), ('BMI', 'Bmi'), ('CSE', 'Cse'), ('ECE', 'Ece'), ('N/A', 'None')], default='N/A', max_length=3)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('AMS', 'Ams'), ('BMI', 'Bmi'), ('CSE', 'Cse'), ('ECE', 'Ece'), ('N/A', 'None')], default='N/A', max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('(N/A)', 'Not Applicable')], default='Fall', max_length=6)),
                ('year', models.IntegerField(default=2021)),
                ('is_current_semester', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sbu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='unknown', max_length=100)),
                ('last_name', models.CharField(default='unknown', max_length=100)),
                ('gpa', models.FloatField(default=4.0)),
                ('email', models.CharField(max_length=100)),
                ('graduated', models.BooleanField(default=False)),
                ('withdrew', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('semesters_enrolled', models.IntegerField(default=1)),
                ('satisfied_courses', models.IntegerField(default=0)),
                ('unsatisfied_courses', models.IntegerField(default=0)),
                ('pending_courses', models.IntegerField(default=0)),
                ('valid_schedule', models.BooleanField(default=True)),
                ('schedule_completed', models.BooleanField(default=False)),
                ('entry_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_semester', to='mast.semester')),
                ('graduation_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_semester', to='mast.semester')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.major')),
                ('requirement_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_semester', to='mast.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_gpa', models.FloatField(default=3.0)),
                ('thesis_required', models.BooleanField(default=False)),
                ('project_required', models.BooleanField(default=False)),
                ('minimum_credits_required', models.IntegerField(default=30)),
                ('number_of_areas', models.IntegerField(default=1)),
                ('total_requirements', models.IntegerField(default=1)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.major')),
            ],
        ),
        migrations.CreateModel(
            name='TrackCourseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=50)),
                ('size', models.IntegerField(default=1)),
                ('limiter', models.BooleanField(default=False)),
                ('upper_limit', models.IntegerField(default=100)),
                ('lower_limit', models.IntegerField(default=999)),
                ('department_limit', models.CharField(choices=[('AMS', 'Ams'), ('BMI', 'Bmi'), ('CSE', 'Cse'), ('ECE', 'Ece'), ('N/A', 'None')], default='N/A', max_length=3)),
                ('parent_course_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mast.trackcourseset')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.track')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.courseinstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.track'),
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.course')),
                ('course_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.courseprerequisiteset')),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='requirement_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.semester'),
        ),
        migrations.CreateModel(
            name='CourseToCourseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('XOR', 'Xor'), ('Concurrency', 'Forbidden Concurrency'), ('None', 'None')], default='None', max_length=20)),
                ('primary_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_course', to='mast.course')),
                ('related_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_course', to='mast.course')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.track')),
            ],
        ),
        migrations.CreateModel(
            name='CoursesTakenByStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('A-', 'A Minus'), ('B+', 'B Plus'), ('B', 'B'), ('B-', 'B Minus'), ('C+', 'C Plus'), ('C', 'C'), ('C-', 'C Minus'), ('D+', 'D Plus'), ('D', 'D'), ('D-', 'D Minus'), ('F', 'F'), ('W', 'Withdrew'), ('S', 'Satisfied'), ('U', 'Unsatisfied'), ('I', 'Incomplete'), ('N/A', 'Not Applicable')], default='N/A', max_length=3)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=15)),
                ('credits_taken', models.IntegerField(default=3)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.courseinstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInTrackSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('each_semester', models.BooleanField(default=False)),
                ('how_many_semesters', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.course')),
                ('course_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.trackcourseset')),
            ],
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.semester'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='no auth', max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('post_date', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.student')),
            ],
        ),
    ]
