# Generated by Django 3.1.7 on 2021-03-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=3)),
                ('number', models.IntegerField()),
                ('timeslot', models.TimeField()),
                ('section', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement_Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('(N/A)', 'Not Applicable')], default='Fall', max_length=6)),
                ('year', models.IntegerField(default=2021)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('(N/A)', 'Not Applicable')], default='Fall', max_length=6)),
                ('year', models.IntegerField(default=2021)),
                ('is_current_semester', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sbu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='unknown', max_length=100)),
                ('last_name', models.CharField(default='unknown', max_length=100)),
                ('gpa', models.FloatField(default=4.0)),
                ('email', models.CharField(max_length=100)),
                ('graduation_season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('(N/A)', 'Not Applicable')], default='(N/A)', max_length=6)),
                ('graduation_year', models.IntegerField(default=0)),
                ('graduated', models.BooleanField(default=False)),
                ('withdrew', models.BooleanField(default=False)),
                ('satisfied_courses', models.IntegerField(default=0)),
                ('unsatisfied_courses', models.IntegerField(default=0)),
                ('pending_courses', models.IntegerField(default=0)),
                ('valid_schedule', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=100)),
                ('entry_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.semester')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.major')),
                ('requirement_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.requirement_semester')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks_in_Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_gpa', models.FloatField(default=3.0)),
                ('thesis_required', models.BooleanField(default=False)),
                ('project_required', models.BooleanField(default=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.major')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Course_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.tracks_in_major'),
        ),
        migrations.CreateModel(
            name='Required_Classes_for_Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=50)),
                ('required_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.course')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite_Classes_for_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_name', models.CharField(max_length=100)),
                ('prerequisite_department', models.CharField(max_length=3)),
                ('prerequisite_number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.course')),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='requirement_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.requirement_semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.semester'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='no auth', max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('post_date', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.student')),
            ],
        ),
        migrations.CreateModel(
            name='Classes_Taken_by_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('A-', 'A Minus'), ('B+', 'B Plus'), ('B', 'B'), ('B-', 'B Minus'), ('C+', 'C Plus'), ('C', 'C'), ('C-', 'C Minus'), ('D+', 'D Plus'), ('D', 'D'), ('D-', 'D Minus'), ('F', 'F'), ('W', 'Withdrew'), ('S', 'Satisfied'), ('U', 'Unsatisfied'), ('I', 'Incomplete'), ('N/A', 'Not Applicable')], default='N/A', max_length=3)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=15)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.student')),
            ],
        ),
    ]
