# Generated by Django 3.1.7 on 2021-03-31 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestakenbystudent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.courseinstance'),
        ),
    ]
