# Generated by Django 3.1.7 on 2021-03-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='entry_semester_season',
            field=models.CharField(choices=[('WN', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FA', 'Fall')], default='FA', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_semester_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_semester_season',
            field=models.CharField(choices=[('WN', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FA', 'Fall')], default='FA', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_semester_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='student',
            name='requirement_semester_season',
            field=models.CharField(choices=[('WN', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FA', 'Fall')], default='FA', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='requirement_semester_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='student',
            name='sbu_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
