# Generated by Django 3.1.7 on 2021-03-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
