# Generated by Django 3.1.7 on 2021-04-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(default='N/A', max_length=4),
        ),
        migrations.AlterField(
            model_name='director',
            name='department',
            field=models.CharField(default='N/A', max_length=4),
        ),
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(default='N/A', max_length=4),
        ),
        migrations.AlterField(
            model_name='trackcourseset',
            name='department_limit',
            field=models.CharField(default='N/A', max_length=4),
        ),
    ]
