# Generated by Django 3.1.7 on 2021-04-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseschedule',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=15),
        ),
    ]
