# Generated by Django 3.1.7 on 2021-04-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseschedule',
            name='ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentcourseschedule',
            name='schedule_type',
            field=models.CharField(choices=[('Smart', 'Smart'), ('Classic', 'Classic'), ('None', 'Default')], default='None', max_length=10),
        ),
    ]
