# Generated by Django 3.1.7 on 2021-04-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='minimum_credits_required',
            field=models.IntegerField(default=30),
        ),
    ]
