# Generated by Django 3.1.7 on 2021-04-05 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0002_auto_20210404_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcourseset',
            name='parent_course_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mast.trackcourseset'),
        ),
    ]
