# Generated by Django 3.1.7 on 2021-03-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0002_auto_20210313_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_semester_season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_semester_season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='requirement_semester_season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', max_length=6),
        ),
    ]
