# Generated by Django 3.1.7 on 2021-04-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0002_auto_20210425_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseschedule',
            old_name='ID',
            new_name='schedule_id',
        ),
    ]
