# Generated by Django 3.1.7 on 2021-04-10 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0002_auto_20210407_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprerequisiteset',
            name='parent_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mast.courseinstance'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.courseinstance'),
        ),
        migrations.AlterField(
            model_name='trackcourseset',
            name='name',
            field=models.CharField(default='Default', max_length=200),
        ),
    ]
