# Generated by Django 3.1.7 on 2021-03-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0002_auto_20210328_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.IntegerField(default=1),
        ),
    ]
