# Generated by Django 3.1.7 on 2021-04-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0003_auto_20210410_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='number_of_areas',
        ),
    ]
