# Generated by Django 3.1.7 on 2021-03-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0003_auto_20210313_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_semester_season',
            field=models.CharField(choices=[('WN', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FA', 'Fall')], default='FA', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_semester_season',
            field=models.CharField(choices=[('WN', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FA', 'Fall')], default='FA', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='requirement_semester_season',
            field=models.CharField(choices=[('WN', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FA', 'Fall')], default='FA', max_length=2),
        ),
    ]
