# Generated by Django 3.1.7 on 2021-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0004_remove_track_number_of_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestakenbystudent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Transfer', 'Transfer')], default='Pending', max_length=15),
        ),
    ]
