# Generated by Django 3.1.7 on 2021-04-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0004_courseintrackset_how_many_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcourseset',
            name='department_limit',
            field=models.CharField(choices=[('AMS', 'Ams'), ('BMI', 'Bmi'), ('CSE', 'Cse'), ('ECE', 'Ece'), ('N/A', 'None')], default='N/A', max_length=3),
        ),
    ]
