# Generated by Django 3.1.7 on 2021-03-14 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0005_auto_20210313_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('track', models.CharField(max_length=50)),
                ('requirement_semester_season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', max_length=6)),
                ('requirement_semester_year', models.IntegerField(default=2021)),
                ('thesis_required', models.BooleanField(default=False)),
                ('project_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.major'),
        ),
    ]
