# Generated by Django 3.1.7 on 2021-04-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0005_trackcourseset_department_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprerequisiteset',
            name='parent_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mast.courseprerequisiteset'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='No class description.', max_length=400),
        ),
    ]
