# Generated by Django 3.1.7 on 2021-04-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0005_auto_20210411_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcourseset',
            name='lower_credit_limiit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='trackcourseset',
            name='upper_credit_limit',
            field=models.IntegerField(default=3),
        ),
    ]
