# Generated by Django 3.1.7 on 2021-04-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0006_auto_20210405_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credits',
            new_name='lower_credit_limit',
        ),
        migrations.AddField(
            model_name='course',
            name='upper_credit_limit',
            field=models.IntegerField(default=3),
        ),
    ]
