# Generated by Django 3.1.7 on 2021-03-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0006_auto_20210314_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('semester_season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', max_length=6)),
                ('semester_year', models.IntegerField()),
                ('timeslot', models.TimeField()),
                ('section', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Required_Classes_for_Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_class_department', models.CharField(max_length=10)),
                ('required_class_number', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.major')),
            ],
        ),
    ]
