# Generated by Django 3.1.7 on 2021-03-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0007_course_required_classes_for_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes_Taken_by_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_id', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.student')),
            ],
        ),
    ]
