# Generated by Django 3.1.7 on 2021-04-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0007_auto_20210406_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='total_requirements',
            field=models.IntegerField(default=1),
        ),
    ]
