# Generated by Django 3.1.7 on 2021-04-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0007_trackcourseset_credit_limiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackcourseset',
            name='credit_limiter',
        ),
        migrations.RemoveField(
            model_name='trackcourseset',
            name='lower_credit_limiit',
        ),
        migrations.RemoveField(
            model_name='trackcourseset',
            name='upper_credit_limit',
        ),
    ]
