# Generated by Django 3.1.7 on 2021-03-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0008_classes_taken_by_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
