# Generated by Django 3.1.7 on 2021-04-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0008_auto_20210412_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcourseset',
            name='lower_credit_limit',
            field=models.BooleanField(default=0),
        ),
    ]
