# Generated by Django 3.1.7 on 2021-04-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0008_track_total_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestakenbystudent',
            name='credits_taken',
            field=models.IntegerField(default=3),
        ),
    ]
