# Generated by Django 3.1.7 on 2021-03-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0009_remove_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes_taken_by_student',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='classes_taken_by_student',
            name='course_name',
        ),
        migrations.AddField(
            model_name='classes_taken_by_student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.course'),
        ),
    ]
