# Generated by Django 3.1.7 on 2021-04-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0009_trackcourseset_lower_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcourseset',
            name='lower_credit_limit',
            field=models.IntegerField(default=0),
        ),
    ]
