# Generated by Django 3.1.7 on 2021-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0010_auto_20210412_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcourseset',
            name='leeway',
            field=models.IntegerField(default=0),
        ),
    ]
