# Generated by Django 3.1.7 on 2021-03-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0010_auto_20210314_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes_taken_by_student',
            name='grade',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
