# Generated by Django 3.1.7 on 2021-03-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0011_classes_taken_by_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_taken_by_student',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A Minus'), ('B+', 'B Plus'), ('B', 'B'), ('B-', 'B Minus'), ('C+', 'C Plus'), ('C', 'C'), ('C-', 'C Minus'), ('D+', 'D Plus'), ('D', 'D'), ('D-', 'D Minus'), ('F', 'F'), ('W', 'Withdrew'), ('S', 'Satisfied'), ('U', 'Unsatisfied'), ('I', 'Incomplete'), ('N/A', 'Not Applicable')], default='N/A', max_length=3),
        ),
    ]
