# Generated by Django 3.1.7 on 2021-04-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0011_trackcourseset_leeway'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseschedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Transfer', 'Transfer')], default='Pending', max_length=15),
        ),
    ]
