# Generated by Django 3.1.7 on 2021-03-15 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0012_auto_20210314_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='required_classes_for_major',
            name='required_class_department',
        ),
        migrations.RemoveField(
            model_name='required_classes_for_major',
            name='required_class_number',
        ),
        migrations.AddField(
            model_name='required_classes_for_major',
            name='required_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.course'),
        ),
    ]
