# Generated by Django 3.1.7 on 2021-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0012_studentcourseschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='credits_taken',
            field=models.IntegerField(default=0),
        ),
    ]
