# Generated by Django 3.1.7 on 2021-03-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0013_auto_20210314_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes_taken_by_student',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
