# Generated by Django 3.1.7 on 2021-03-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0014_classes_taken_by_student_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_taken_by_student',
            name='in_progress',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], default='In Progress', max_length=15),
        ),
    ]
