# Generated by Django 3.1.7 on 2021-03-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0016_auto_20210315_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='surname', max_length=100),
            preserve_default=False,
        ),
    ]
