# Generated by Django 3.1.7 on 2021-03-15 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0020_auto_20210315_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 17, 57, 52, 91485)),
        ),
    ]
