# Generated by Django 3.1.7 on 2021-03-15 22:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0022_auto_20210315_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Required_Classes_for_Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=50)),
                ('thesis_required', models.BooleanField(default=False)),
                ('project_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='major',
            name='project_required',
        ),
        migrations.RemoveField(
            model_name='major',
            name='thesis_required',
        ),
        migrations.RemoveField(
            model_name='major',
            name='track',
        ),
        migrations.AddField(
            model_name='student',
            name='track',
            field=models.CharField(default='default track', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 18, 11, 59, 265282)),
        ),
        migrations.DeleteModel(
            name='Required_Classes_for_Major',
        ),
        migrations.AddField(
            model_name='required_classes_for_track',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.major'),
        ),
        migrations.AddField(
            model_name='required_classes_for_track',
            name='required_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.course'),
        ),
    ]
