# Generated by Django 3.1.7 on 2021-03-15 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0025_auto_20210315_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
