# Generated by Django 3.1.7 on 2021-03-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0030_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='track',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
