# Generated by Django 3.1.7 on 2021-03-15 22:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0031_auto_20210315_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='no auth', max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('post_date', models.DateTimeField(default=datetime.datetime(2021, 3, 15, 18, 44, 45, 504930))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.student')),
            ],
        ),
    ]
