# Generated by Django 3.1.7 on 2021-03-15 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0035_auto_20210315_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.CharField(default=datetime.datetime(2021, 3, 15, 18, 58, 42, 694076), max_length=100),
        ),
    ]
