# Generated by Django 3.1.7 on 2021-03-15 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0037_auto_20210315_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.CharField(default=datetime.datetime(2021, 3, 15, 19, 8, 7, 986484), max_length=100),
        ),
    ]
