# Generated by Django 3.1.7 on 2021-03-15 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0038_auto_20210315_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.CharField(default=datetime.datetime(2021, 3, 15, 19, 9, 26, 92736), max_length=100),
        ),
        migrations.AlterField(
            model_name='tracks_in_major',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.major'),
        ),
    ]
