# Generated by Django 3.1.7 on 2021-03-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0040_auto_20210315_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.CharField(max_length=100),
        ),
    ]
