# Generated by Django 3.1.7 on 2021-03-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0041_auto_20210315_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks_in_major',
            name='required_gpa',
            field=models.FloatField(default=3.0),
        ),
    ]
