# Generated by Django 3.1.7 on 2021-03-16 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0042_tracks_in_major_required_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pending_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='satisfied_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='unsatisfied_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes_taken_by_student',
            name='status',
            field=models.CharField(choices=[('Satisfied', 'Satisfied'), ('Pending', 'Pending'), ('Unsatisfied', 'Unsatisfied')], default='Pending', max_length=15),
        ),
        migrations.CreateModel(
            name='Prerequisite_Classes_for_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_name', models.CharField(max_length=100)),
                ('prerequisite_department', models.CharField(max_length=10)),
                ('prerequisite_number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mast.course')),
            ],
        ),
    ]
