# Generated by Django 3.1.7 on 2021-03-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0043_auto_20210315_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='valid_schedule',
            field=models.BooleanField(default=True),
        ),
    ]
