# Generated by Django 3.1.7 on 2021-03-17 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0045_auto_20210316_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement_Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', max_length=6)),
                ('year', models.IntegerField(default=2021)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Fall', max_length=6)),
                ('year', models.IntegerField(default=2021)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester_season',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester_year',
        ),
        migrations.RemoveField(
            model_name='major',
            name='requirement_semester_season',
        ),
        migrations.RemoveField(
            model_name='major',
            name='requirement_semester_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entry_semester_season',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entry_semester_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduation_semester_season',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduation_semester_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='requirement_semester_season',
        ),
        migrations.RemoveField(
            model_name='student',
            name='requirement_semester_year',
        ),
        migrations.RemoveField(
            model_name='student_course_schedule',
            name='season',
        ),
        migrations.RemoveField(
            model_name='student_course_schedule',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.semester'),
        ),
        migrations.AddField(
            model_name='major',
            name='requirement_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='requirement_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.requirement_semester'),
        ),
    ]
