# Generated by Django 3.1.7 on 2021-03-17 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0046_auto_20210316_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='requirement_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mast.requirement_semester'),
        ),
    ]
