# Generated by Django 3.1.7 on 2021-03-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0047_auto_20210316_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='required_classes_for_track',
            name='major',
        ),
        migrations.RemoveField(
            model_name='required_classes_for_track',
            name='project_required',
        ),
        migrations.RemoveField(
            model_name='required_classes_for_track',
            name='thesis_required',
        ),
        migrations.AddField(
            model_name='tracks_in_major',
            name='project_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracks_in_major',
            name='thesis_required',
            field=models.BooleanField(default=False),
        ),
    ]
