# Generated by Django 3.1.7 on 2021-03-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0050_auto_20210317_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='DEF', max_length=3),
        ),
    ]
