# Generated by Django 3.1.7 on 2021-03-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0051_auto_20210317_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(default='BMI', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='director',
            name='department',
            field=models.CharField(default='BMI', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(default='BMI', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prerequisite_classes_for_course',
            name='prerequisite_department',
            field=models.CharField(max_length=3),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
