# Generated by Django 3.1.7 on 2021-03-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0052_auto_20210317_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_current_semester',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
