# Generated by Django 3.1.7 on 2021-03-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0053_auto_20210319_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('N/A', 'Not Applicable')], default='N/A', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement_semester',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('N/A', 'Not Applicable')], default='Fall', max_length=6),
        ),
        migrations.AlterField(
            model_name='semester',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('N/A', 'Not Applicable')], default='Fall', max_length=6),
        ),
    ]
