# Generated by Django 3.1.7 on 2021-03-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0054_auto_20210321_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement_semester',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('(N/A)', 'Not Applicable')], default='Fall', max_length=6),
        ),
        migrations.AlterField(
            model_name='semester',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('(N/A)', 'Not Applicable')], default='Fall', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('(N/A)', 'Not Applicable')], default='(N/A)', max_length=6),
        ),
    ]
