# Generated by Django 3.1.7 on 2021-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0055_auto_20210322_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_taken_by_student',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=15),
        ),
    ]
