# Generated by Django 3.1.7 on 2021-03-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0056_auto_20210323_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='id',
        ),
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
