# Generated by Django 3.1.7 on 2021-03-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0058_auto_20210327_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='department',
        ),
        migrations.RemoveField(
            model_name='major',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='tracks_in_major',
            name='major',
        ),
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
