# Generated by Django 3.1.7 on 2021-03-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast', '0059_auto_20210327_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(max_length=3),
        ),
    ]
